# Generated by Django 5.1 on 2024-10-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_violencia', '0003_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='usuario_anónimo', max_length=150, unique=True),
        ),
    ]
