# Generated by Django 5.1 on 2024-10-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_violencia', '0004_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
