# Generated by Django 5.1 on 2024-10-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_violencia', '0005_video_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
