# Generated by Django 5.1 on 2024-11-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_violencia', '0006_remove_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion_violencia.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='prediction',
            field=models.BooleanField(default=False),
        ),
    ]
