# Generated by Django 5.1 on 2024-11-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_violencia', '0007_feedback_thumbnail_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
