# Generated by Django 5.1 on 2024-11-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_violencia', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelto'), ('failed', 'No resuelto')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='feedback_status',
            field=models.CharField(choices=[('none', 'Sin feedback'), ('incorrect', 'Feedback incorrecto'), ('resolved', 'Feedback resuelto')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='is_file_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
